// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/orders.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// todo implement messages
type Drink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drink) Reset() {
	*x = Drink{}
	mi := &file_pb_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Drink) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drink) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Drink) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	DrinkId       uint64                 `protobuf:"varint,2,opt,name=DrinkId,proto3" json:"DrinkId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pb_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetDrinkId() uint64 {
	if x != nil {
		return x.DrinkId
	}
	return 0
}

type GetDrinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drinks        []*Drink               `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDrinksResponse) Reset() {
	*x = GetDrinksResponse{}
	mi := &file_pb_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrinksResponse) ProtoMessage() {}

func (x *GetDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrinksResponse.ProtoReflect.Descriptor instead.
func (*GetDrinksResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{2}
}

func (x *GetDrinksResponse) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_pb_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrinkId       uint64                 `protobuf:"varint,1,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_pb_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{4}
}

func (x *OrderRequest) GetDrinkId() uint64 {
	if x != nil {
		return x.DrinkId
	}
	return 0
}

func (x *OrderRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_pb_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{5}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_pb_orders_proto protoreflect.FileDescriptor

const file_pb_orders_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/orders.proto\x12\x06models\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"U\n" +
	"\x05Drink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\"9\n" +
	"\x05Order\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x18\n" +
	"\aDrinkId\x18\x02 \x01(\x04R\aDrinkId\":\n" +
	"\x11GetDrinksResponse\x12%\n" +
	"\x06drinks\x18\x01 \x03(\v2\r.models.DrinkR\x06drinks\":\n" +
	"\x11GetOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.models.OrderR\x06orders\"A\n" +
	"\fOrderRequest\x12\x19\n" +
	"\bdrink_id\x18\x01 \x01(\x04R\adrinkId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"4\n" +
	"\rOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.models.OrderR\x05order2\xcf\x01\n" +
	"\fOrderService\x12@\n" +
	"\tGetDrinks\x12\x16.google.protobuf.Empty\x1a\x19.models.GetDrinksResponse\"\x00\x12@\n" +
	"\tGetOrders\x12\x16.google.protobuf.Empty\x1a\x19.models.GetOrdersResponse\"\x00\x12;\n" +
	"\n" +
	"OrderDrink\x12\x14.models.OrderRequest\x1a\x15.models.OrderResponse\"\x00B\tZ\aexc8/pbb\x06proto3"

var (
	file_pb_orders_proto_rawDescOnce sync.Once
	file_pb_orders_proto_rawDescData []byte
)

func file_pb_orders_proto_rawDescGZIP() []byte {
	file_pb_orders_proto_rawDescOnce.Do(func() {
		file_pb_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)))
	})
	return file_pb_orders_proto_rawDescData
}

var file_pb_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_orders_proto_goTypes = []any{
	(*Drink)(nil),             // 0: models.Drink
	(*Order)(nil),             // 1: models.Order
	(*GetDrinksResponse)(nil), // 2: models.GetDrinksResponse
	(*GetOrdersResponse)(nil), // 3: models.GetOrdersResponse
	(*OrderRequest)(nil),      // 4: models.OrderRequest
	(*OrderResponse)(nil),     // 5: models.OrderResponse
	(*emptypb.Empty)(nil),     // 6: google.protobuf.Empty
}
var file_pb_orders_proto_depIdxs = []int32{
	0, // 0: models.GetDrinksResponse.drinks:type_name -> models.Drink
	1, // 1: models.GetOrdersResponse.orders:type_name -> models.Order
	1, // 2: models.OrderResponse.order:type_name -> models.Order
	6, // 3: models.OrderService.GetDrinks:input_type -> google.protobuf.Empty
	6, // 4: models.OrderService.GetOrders:input_type -> google.protobuf.Empty
	4, // 5: models.OrderService.OrderDrink:input_type -> models.OrderRequest
	2, // 6: models.OrderService.GetDrinks:output_type -> models.GetDrinksResponse
	3, // 7: models.OrderService.GetOrders:output_type -> models.GetOrdersResponse
	5, // 8: models.OrderService.OrderDrink:output_type -> models.OrderResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_orders_proto_init() }
func file_pb_orders_proto_init() {
	if File_pb_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_orders_proto_goTypes,
		DependencyIndexes: file_pb_orders_proto_depIdxs,
		MessageInfos:      file_pb_orders_proto_msgTypes,
	}.Build()
	File_pb_orders_proto = out.File
	file_pb_orders_proto_goTypes = nil
	file_pb_orders_proto_depIdxs = nil
}
